### ISSUE TITLE
Propuesta checklist de procesos

### ISSUE THREAD

**Issue by albertcastaned** [Solify-IT/docs#11]
## Objetivos
* Verificar que los procesos cumplan con los estándares del departamento para la documentación de los procesos.

## Checklist
- [ ] El título del proceso tiene un identificador único y un nombre como verbo en infinitivo. (Ejemplo: Mejorar, Conducir, Crear)
- [ ] El proceso cubre los apartados que contiene la [plantilla de procesos](https://github.com/Solify-IT/docs/wiki/P00---Plantilla-para-procesos)
- [ ] Las prácticas de CMMI incluidas en las etapas del proceso están completas y correctas
- [ ] El proceso no tiene faltas ortográficas o errores gramaticales.
- [ ] La sintaxis de markdown funciona.

**Comment by albertcastaned** [comment]
@Solify-IT/wiki-owners
