### ISSUE TITLE
Propuesta - Checklist para revisión de guías

### ISSUE THREAD

**Issue by LaloGlzMlz** [Solify-IT/docs#17]
## Objetivos
* Verificar que las guías cumplan con los estándares del departamento para la documentación de guías.

## Checklist
- [ ] El título de la guía comienza con G#, en donde # es un número único igual al número de la última guía +1, seguido de un nombre descriptivo, relevante a lo que la guía detalla comenzando por un sustantivo común o propio (Ejemplos: G04 Product Owner, G08 Propuestas de mejora continua).
- [ ] El primer apartado en la guía se llama "Descripción" y en este se da una breve descripción del propósito de existir de la guía en cuestión.
- [ ] En caso de ser una guía que propone mejora continua, esta sigue las especificaciones que describe la [G08 Propuestas de mejora continua](https://github.com/Solify-IT/docs/wiki/G08-Propuestas-de-mejora-continua).
- [ ] La redacción de la guía no tiene faltas ortográficas ni errores gramaticales.
- [ ] La sintaxis de markdown funciona.

**Comment by LaloGlzMlz** [comment]
@Solify-IT/wiki-owners @Topi99

**Comment by Topi99** [comment]
LGTM 💯

**Comment by albertcastaned** [comment]
Lo veo bien solo que por el segundo punto tendriamos que anotar la tarea de actualizar las guías existentes que no tienen el campo. 🤔

**Comment by LaloGlzMlz** [comment]
Yo lo puedo hacer de una vez, opinas que es un apartado que deberíamos incluir?

**Comment by albertcastaned** [comment]
Creo que si estaria bien. Ya revisamos esta propuesta dos personas así que pienso que ya la podemos pasar a la wiki. 

> Yo lo puedo hacer de una vez, opinas que es un apartado que deberíamos incluir?

**Comment by LaloGlzMlz** [comment]
va
