### ISSUE TITLE
CL5 -  Checklist para Documentación de Cambios de Requisitos

### ISSUE THREAD

**Issue by domerent97** [Solify-IT/docs#47]
# CL5 -  Checklist para Documentación de Cambios de Requerimientos

Al realizar un cambio en los requerimientos, se deben documentar dichos cambios en la Bitácora de Cambios de la Matriz de Trazabilidad. 
La documentación incluye:

- [ ] Fecha del cambio

- [ ] Resumen donde se explica el qué y por qué del cambio

- [ ] Tipo de cambio (ej. Nuevo requisito, cambio de requisito)

- [ ] Requisitos afectados por dicho cambio

- [ ] Impacto del cambio (Nuevo requisito -> Bajo, Cambio de requisito -> Medio)

- [ ] Notas

**Comment by albertcastaned** [comment]
Lo veo bien.

**Comment by albertcastaned** [comment]
Este no le veo problema incorporandolo a la wiki. Lo puedes cerrar e incorporar a la wiki? @domerent97

**Comment by Topi99** [comment]
:shipit:
