### ISSUE TITLE
Cambios a la checklist de revisión

### ISSUE THREAD

**Issue by A01702321** [Solify-IT/docs#59]
- [ ] Arquitectura: 
    - [ ] Solo importar módulos o código de niveles inferiores de la arquitectura.
    - [ ] Usar inyección de dependencias con dependencias de niveles superiores.
    - [ ] Los archivos están colocados en la carpeta donde corresponden
- [ ] Casos especiales y limites:
    - [ ] El programa esta protegido de overflows, underflows, y condiciones fuera de limites.
- [ ] Uso funcional:
    - [ ] Todas las funciones, métodos y clases se entienden completamente y son utilizados correctamente.
    - [ ] Todas las implementaciones de abstracciones o interfaces están definidas.
- [ ] Consideraciones del sistema:
    - [ ] El programa no causa errores de límite de memoria.
    - [ ] El programa no permite inyección SQL.
    - [ ] El programa no revela información confidencial
    - [ ] Llaves secretas son guardadas en variables de entorno y no en código.
- [ ] Nombres:
    - [ ] Nombres de clases, variables, objetos, tipos e interfaces están en inglés.
    - [ ] Nombres de tablas y campos de tablas están en snake_case.
    - [ ] El default export debe tener el mismo nombre del archivo en el que se encuentra escrito. 
- [ ] Estándares:
    - [ ] No hay errores con ESLint
    - [ ] Se sigue el estándar [AirBnB](https://github.com/airbnb/javascript).
- [ ] Llamadas:
    - [ ] Cuando se llama una función asíncrona, siempre manejar un posible error.
    - [ ] Usar spreads `...` para copiar arreglos u objetos. 
- [ ] Strings:
    - [ ] Usar comillas sencillas (`''`) para cadenas de texto.
    - [ ] Usar comillas dobles (`""`) para cadenas de texto en props de React.
    - [ ] Cuando se construyen cadenas con "parámetros", usar template strings.

**Comment by A01702321** [comment]
Agregar que se cumpla el ESLint que cubre la parte de commas, nombres de tpos y objetos y removí tareas que eran obvias.
